---

name: test
on:
  push:

jobs:
  test:
    strategy:
      matrix:
        version:
          - '1.22-alpine'
          - '1.23-alpine'
          - alpine

    defaults:
      run:
        shell: sh

    container:
      image: golang:${{ matrix.version }}
      env:
        CGO_ENABLED: 0
        GOPATH: /go

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: go test
        run: |
          apk --no-cache add openssl && \
          go test -v -cover

...
